# Fetching the latest node image on alpine linux
# יבו אאחת הספריות ליצירת ה image.
FROM node:alpine AS development

# Declaring env
# בחירת הסביבה - הגירסא
ENV NODE_ENV development

# Setting up the work directory
WORKDIR /react-app

# Installing dependencies
# העתקת כל הקבצים לתוך הimage
COPY . . 
# התקנה והרצת הקוד
RUN npm install

# # Copying all the files in our project
# COPY . .

# Starting our application
CMD ["npm","start"]

